### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by vincentmaule** [OptimisticShaggy/LAB-101-html-editor-and-basic-elements#1]
## Build a résumé for a fictional character, applying for a fake (and ideally ridiculous) job

@egillespie Can you take a look at this? It's [hosted here](https://OptimisticShaggy.github.io/LAB-101-html-editor-and-basic-elements/index.html) and meets the following criteria:

- [x] Each of the following elements is used appropriately, at least once: `h1`, `h2`, `p`, `img`, `li`, `a`
- [x] At least one of the following elements is used: `ol`, `ul`
- [x] At least one external image is used and links to the page it came from

**Comment by egillespie** [comment]
I really like the splash of semantic HTML elements in here such as `header`, `address`, and `section`. Those are nice additions that will make the page more accessible and easier to style. 😁 

The layout and use of elements introduced in this lesson are really good too. You've definitely got the hang of using HTML elements — your paragraphs, anchors, and image are all spot on. 👍 

Here are some recommendations to improve how you're using some of the elements introduced in the lesson. Can you give these a try?

### 1. Move `h1` elements out of the lists

Heading elements (`h1`, `h2`, etc.) are often used as a title or name for a new portion of content in a document. Lists, on the other hand, connect a series of similar pieces of information.

I think on your resume it makes sense to place the `h1` elements _above_ the lists, like this:

``` html
<h1>Vincent Maul</h1>
<ul>
  <li>Lansing, Michigan</li>
  <li>vincent.maule@gmail.com</li>
  <li>248-946-7297</li>
</ul>
```

This way the headings are used to introduce the lists instead of being a part of the list. It may be more clear with the second `h1` on your page: "Experience" is the title for that part of the page and not an actual job or work experience so it doesn't belong in a list with Comcast and Hi-Lex Controls.

Would you mind moving your `h1` elements above the lists as shown in my example?

While you're at it, I recommend changing all but your first `h1` to an `h2` element. There is often only one `h1` element on a page to show the page title and all other headings are subsections of the title. Search engines also give better rankings to pages that only have one `h1` element. 😉 

### 2. Put all of your jobs in one ordered list

Since all of your work experience has a chronology to it and are related by the fact that they are all jobs you held/hold, I think it makes sense to combine your work experience into one big ordered list like this:

``` html
<h2>Experience</h2>
<ol>
  <li>
    <h3>Comcast</h3>
    <ul>
      <li>Oct. 2017 - Present</li>
      <li>Work number: ...</li>
      <li>Job title: ...</li>
      <li>
        <ul>
          <li><h3>Efficient Problem Solving:</h3>...</li>
          <li><h3>Team Player:</h3>...</li>
          ...
        </ul>
    </ul>
  </li>
  <li>
    <h3>Hi-Lex Controls</h3>
    <ul>
      <li>Aug. 2015 - Oct. 2017</li>
      <li>Dirk LaPratt: ...</li>
      <li>Job title: ...</li>
      <li>
        <ul>
          <li><h3>Efficient Problem Solving:</h3>...</li>
          <li><h3>Team Player:</h3>...</li>
          ...
        </ul>
    </ul>
  </li>
</ol>
```

This will make the information on your page more accessible, better connect your work history chronologically, and should be easier to style down the road.

Don't worry about the bullets and numbers on the lists for now. If you don't want them, there are ways to hide/change them with CSS.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🤘

**Comment by vincentmaule** [comment]
Thank you for laying out some more of the features for HTML with the semantics. That makes sense with the H1 Headings and I hope I can learn more about H2 and H3. I know I'm gonna get it as time passes but one step at a time. I was able to get most of what was mentioned corrected except one that I was having trouble with. Ironically enough, W3 Validator sees that lists are not a sub element of lists.
`Element ul not allowed as child of element ol in this context. (Suppressing further errors from this subtree.)`
But what is really getting to me is how each job is not in an ordered list correctly. I took a good half an hour looking at it, would there be a chance you could give a look into it?

**Comment by egillespie** [comment]
Your changes look pretty good and I think I can explain a little better what the validator is reporting. Check these out:

### Stray end tag `img`

The `img` element doesn't need a closing `</img>` tag because it doesn't have any nested content — nothing every really goes between the `<img>` and `</img>` tags. So valid HTML expects `img` elements to be formatted as `<img src="..." alt="...">` without a subsequent `</img>` tag.

If you remove the `</img>` tag then the error will go away with it.

### Element `ul` not allowed as child of element `ul` in this context

The issue here is that `ul` and `ol` elements only have one valid child element: `li`. If you want to put a list inside of another list, the way to organize the HTML is like this:

``` hml
<ul>
  <li>Unordered item 1</li>
  <li>
    <ol>
      <li>Numbered item 1</li>
      <li>Numbered item 2</li>
    </ol>
  </li>
</ul>
```

In the various spots in your page where you have nested lists, if you wrap the inner list in `<li>` and `</li>` tags, I would expect the errors to go away.

---

Give these a try and see if you can get all of the errors reported by the validator to go away (warnings are okay). Feel free to reach out here or in Slack if you want help too. You've got this! 💪

**Comment by vincentmaule** [comment]
A great lesson to learn from! Happy to learn some more of the semantics. If there is anything you believe I need to change, let me know! Anything I need to add, let me know!

**Comment by egillespie** [comment]
Nice, those changes worked and the results look fantastic. Awesome job! 🎉 :shipit:

**Comment by vincentmaule** [comment]
Learned to work more with styling code and a peek into SEO aspects..
